# Generated by Django 4.2 on 2023-04-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballEssential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='basketball_essentials')),
                ('rating', models.IntegerField()),
                ('coupons', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SoccerEssential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='soccer_essentials')),
                ('rating', models.IntegerField()),
                ('coupons', models.CharField(max_length=200)),
            ],
        ),
    ]
