# Generated by Django 4.1.6 on 2023-05-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0002_basketballessential_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketballessential',
            name='benefits',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='basketballessential',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basketballessential',
            name='coupons',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basketballessential',
            name='material',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='basketballessential',
            name='stars',
            field=models.IntegerField(blank=True),
        ),
    ]
