# Generated by Django 4.1.6 on 2023-05-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0004_alter_basketballessential_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketballessential',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
