# Generated by Django 4.1.6 on 2023-05-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0005_basketballessential_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketballessential',
            name='sale',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
