# Generated by Django 4.1.6 on 2023-06-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0008_basketballessential_compare_img_and_more'),
    ]

    operations = [
    
    ]
