# Generated by Django 4.1.6 on 2023-06-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0010_remove_basketballessential_rating_and_more'),
    ]

    operations = [

    ]
