# Generated by Django 4.1.6 on 2023-06-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0011_remove_basketballessential_compare_price_and_more'),
    ]

    operations = [

    ]
