# Generated by Django 4.1.6 on 2023-06-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0013_alter_basketballessential_compare_price_and_more'),
    ]

    operations = [

    ]
