# Generated by Django 4.1.6 on 2023-06-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0014_rename_compare_price_basketballessential_compare_price1_and_more'),
    ]

    operations = [

    ]
