# Generated by Django 4.1.6 on 2023-06-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0015_rename_compare_price1_basketballessential_compare_price_and_more'),
    ]

    operations = [

    ]
