# Generated by Django 4.1.6 on 2023-06-14 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0017_remove_basketballessential_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(blank=True, max_length=200)),
                ('compare_image', models.ImageField(upload_to='basketball_essentials')),
                ('comp_price', models.IntegerField(blank=True)),
                ('comp_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='basketballessential',
            name='compare_img',
        ),
        migrations.RemoveField(
            model_name='basketballessential',
            name='compare_name',
        ),
    ]
