# Generated by Django 4.1.6 on 2023-06-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0018_comparison_remove_basketballessential_compare_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketballessential',
            name='rating',
        ),
    ]
