# Generated by Django 4.1.6 on 2023-06-14 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0019_remove_basketballessential_rating'),
    ]

    operations = [
    
    ]
