# Generated by Django 4.2 on 2023-06-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0020_basketballessential_compare_card'),
    ]

    operations = [
        
    ]
