# Generated by Django 4.2 on 2023-06-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0021_remove_basketballessential_compare_card_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comparison',
        ),
    ]
