# Generated by Django 4.2 on 2023-06-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0022_delete_comparison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=200, null=True)),
                ('comp_url', models.URLField(null=True)),
                ('comp_img', models.ImageField(null=True, upload_to='basketball_essentials')),
                ('comp_price', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SoccerEssential',
        ),
        migrations.AddField(
            model_name='basketballessential',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='basketballessential',
            name='comparisons',
            field=models.ManyToManyField(blank=True, to='sportsassenapp.comparison'),
        ),
    ]
