# Generated by Django 4.2 on 2023-06-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsassenapp', '0024_alter_basketballessential_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketballessential',
            old_name='comparisons',
            new_name='comparison',
        ),
    ]
